# Generated by Django 4.0.3 on 2022-04-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_to_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='to_url',
        ),
    ]
